myapp/urls.py
from django.urls import path

from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:book_id>/', views.DetailView.as_view(), name='detail'),
    path(r'findbooks/', views.findbooks, name='findbooks'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'review/', views.review, name='review'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'check/<int:book_id>/', views.chk_reviews, name='check_reviews'),
    path(r'register/', views.register, name='register'),
    path(r'orders/', views.my_orders, name='orders'),
]

mysiteF19/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'myapp/', include('myapp.urls1'))
    path(r'myapp/', include('myapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=False, default='USA')

    def __str__(self):
        return self.name


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                validators=[MinValueValidator(0), MaxValueValidator(1000)])
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Member(User):
    STATUS_CHOICES = [
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)
    profile_image = models.ImageField(upload_to='profile_image/', blank=True)

    def __str__(self):
        return self.username

    def books_title(self):
        title = ""
        for book in self.borrowed_books.all():
            title = title + book.title + ", "
        return title[:-2]


class Order(models.Model):
    ORDER_TYPE_CHOICES = [
        (0, 'Purchase'),
        (1, 'Borrow')
    ]
    books = models.ManyToManyField(Book)
    member = models.ForeignKey(Member, related_name='member', on_delete=models.CASCADE)
    order_type = models.IntegerField(choices=ORDER_TYPE_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now())

    def total_items(self):
        return self.books.count()

    def __str__(self):
        return self.member.username + " " + str(self.order_date)


class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.reviewer + " for " + self.book.title + " : " + str(self.rating) + " stars"

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from myapp.models import Order, Review, Member


class SearchForm(forms.Form):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    name = forms.CharField(max_length=100, required=False, label="Your Name")
    category = forms.ChoiceField(widget=forms.RadioSelect, choices=CATEGORY_CHOICES, required=False,
                                 label="Select a category:")
    max_price = forms.DecimalField(label="Maximum Price", required=True, min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'book', 'rating', 'comments']
        widgets = {'book': forms.RadioSelect}
        labels = {'reviewer': u'Please enter a valid email',
                  'rating': u'Rating: An integer between 1 (worst) and 5 (best)'}

    def clean_rating(self):
        rating = self.cleaned_data.get('rating')
        if rating < 1 or rating > 5:
            raise forms.ValidationError('You must enter a rating between 1 and 5!')
        return rating


class RegisterForm(UserCreationForm):
    class Meta:
        model = Member
        fields = ['username', 'password1', 'password2', 'profile_image', 'first_name', 'last_name', 'status', 'address',
                  'city', 'province', 'auto_renew']

myapp/views.py
import random
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm
from .models import Book, Member, Order, Review


# Create your views here.
def index(request):
    last_login = ''
    if 'last_login' in request.session.keys():
        last_login = request.session.get('last_login')
    book_list = Book.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'booklist': book_list, 'last_login': last_login})


class IndexView(View):
    template_name = 'myapp/index.html'
    last_login_cookie = 'last_login'

    def get(self, request):
        last_login = ''
        if self.last_login_cookie in request.session.keys():
            last_login = request.session.get(self.last_login_cookie)

        book_list = Book.objects.all().order_by('id')[:10]
        return render(request, self.template_name, {'booklist': book_list, 'last_login': last_login})


def about(request):
    if request.COOKIES.get('lucky_num'):
        mynum = request.COOKIES.get('lucky_num')
    else:
        mynum = random.randint(1, 100)
    response = render(request, 'myapp/about.html', {'mynum': mynum})
    response.set_cookie('lucky_num', mynum, expires=300)
    return response


def detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    return render(request, 'myapp/detail.html', {'book': book})


class DetailView(View):
    template_name = 'myapp/detail.html'

    def get(self, request, book_id):
        book = get_object_or_404(Book, id=book_id)
        return render(request, self.template_name, {'book': book})


def findbooks(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']
            # booklist = Book.objects.filter(category=category)
            if not category:
                booklist = Book.objects.filter(price__lte=max_price)
            else:
                booklist = Book.objects.filter(price__lte=max_price, category=category)
            return render(request, 'myapp/results.html', {'booklist': booklist, 'name': name, 'category': category})
        else:
            print(form.errors)
            return render(request, 'myapp/findbooks.html', {'form': form, })
    else:
        form = SearchForm()
        return render(request, 'myapp/findbooks.html', {'form': form})


@login_required(login_url='/myapp/login/')
def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            books = form.cleaned_data['books']
            order = form.save(commit=False)
            member = get_object_or_404(Member, id=request.user.id)
            order.member = member
            order.save()
            order.books.set(books)
            type = order.order_type
            if type == 1:
                for b in order.books.all():
                    member.borrowed_books.add(b)
            return render(request, 'myapp/order_response.html', {'books': books, 'order': order})
        else:
            return render(request, 'myapp/placeorder.html', {'form': form})
    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form})


@login_required(login_url='/myapp/login/')
def review(request):
    try:
        member = Member.objects.get(pk=request.user.pk)
        if member.status == 1 or member.status == 2:
            if request.method == 'POST':
                form = ReviewForm(request.POST)
                if form.is_valid():
                    review = form.save()
                    book = review.book
                    book.num_reviews += 1
                    book.save()
                    review.save()
                    return HttpResponseRedirect('/myapp')
            else:
                form = ReviewForm()
            return render(request, 'myapp/review.html', {'form': form})
        else:
            return render(request, 'myapp/invalid.html', {'message': 'You are not eligible to view this page'})
    except Member.DoesNotExist:
        return render(request, 'myapp/invalid.html', {'message': 'You are not eligible to view this page'})


def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('myapp:index'))
    if request.method == 'POST':
        valuenext = request.POST.get('next')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                request.session.set_expiry(3600)
                if valuenext == '':
                    return HttpResponseRedirect(reverse('myapp:index'))
                else:
                    return HttpResponseRedirect(valuenext)
            else:
                return render(request, 'myapp/invalid.html', {'message': 'Your account is disabled.'})
        else:
            return render(request, 'myapp/invalid.html', {'message': 'Invalid login details.'})
    else:
        return render(request, 'myapp/login.html')


@login_required(login_url='/myapp/login/')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url='/myapp/login/')
def chk_reviews(request, book_id):
    if request.user.is_authenticated:
        selected_book = get_object_or_404(Book, pk=book_id)
        if selected_book.num_reviews == 0:
            return render(request, 'myapp/chk_reviews.html', {'book': selected_book, 'avg_rating': -1})
        else:
            reviews = Review.objects.filter(book=selected_book)
            total_rating = 0
            for single_review in reviews:
                total_rating += single_review.rating
            avg_rating = total_rating / len(reviews)
            return render(request, 'myapp/chk_reviews.html', {'book': selected_book, 'avg_rating': avg_rating})
    else:
        return render(request, 'myapp/chk_reviews.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myapp:login'))
    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})


@login_required(login_url='/myapp/login/')
def my_orders(request):
    try:
        logged_in_user = Member.objects.get(pk=request.user.pk)
        orders = Order.objects.filter(member=logged_in_user)

        book_list = []
        for order in orders:
            books = order.books.all()
            book_title = ''
            for book in books:
                book_title = book_title + book.title + ', '
            book_list.append(book_title[:-2])
        new_list = zip(orders, book_list)

        return render(request, 'myapp/myorders.html', {'orders': orders, 'book_list': book_list, 'new_list': new_list})
    except Member.DoesNotExist:
        return render(request, 'myapp/invalid.html', {'message': 'There are no available orders!'})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}About{% endblock %}

{% block body_block %}
    <h2 style="margin-top: 100px; color: #663399;">This is an eBook APP</h2>
    <h4>Lucky number: {{ mynum }}</h4>
    {#    <p><a href="/myapp/">Go to index page</a></p>#}
    {#    <p><a href="{% url 'myapp:index' %}">Go to index page</a></p>#}
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<h2>This is an eBook APP</h2>
<p><a href="/myapp/">Go to index page</a></p>
<p><a href="{% url 'myapp:index' %}">Go to index page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/my_styles.css' %}">

    <title>eBook APP - {% block title %}Welcome!{% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rebeccapurple;">
    <a class="navbar-brand" href="{% url 'myapp:index' %}">eLibrary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto navbar">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'myapp:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:findbooks' %}">Find books</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-outline-danger btn-outline-info my-2 my-sm-0 logout"
                       href="{% url 'myapp:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="btn btn-outline-success btn-outline-info my-2 my-sm-0 login"
                       href="{% url 'myapp:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success btn-outline-info my-2 my-sm-0"
                       href="{% url 'myapp:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>

<div>
    <div class="header">
        {% if  request.user.member.profile_image %}
            <img src="{{ request.user.member.profile_image.url }}"
                 style="border-radius: 50%;    width: 100px; height: 100px;">
        {% endif %}

        {% if user.is_authenticated %}
            <h3 class="user-greeting">{% block myhdg %}Hello {{ user.first_name }} {% endblock %}</h3>
        {% else %}
            <h3 class="user-greeting">{% block myhdg1 %}Hello User {% endblock %}</h3>
        {% endif %}
        {% block body_block %}*** {% endblock %}
    </div>

</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>
</html>

myapp/templates/myapp/chk_reviews.html
{% extends 'myapp/base.html' %}

{% block title %}Check Reviews{% endblock %}

{% block body_block %}
    <div style="margin-top: 100px;">
        {% if avg_rating %}
            {% if avg_rating == -1 %}
                <h5>No reviews for the book:{{ book.title }}
                <h2>
            {% else %}
                <h2><a href="{% url 'myapp:detail' book.id %}">{{ book.title }}</a></h2>
                <h5>Average rating: {{ avg_rating }}</h5>
            {% endif %}
        {% else %}
            <br>
            <strong>You are not a registered member!</strong>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block title %}Detail{% endblock %}

{% block body_block %}

    <div class="card border-info mb-3" style="max-width: 30rem; margin: 100px auto">
        <div class="card-header">About</div>
        <div class="card-body text-info">
            <h3 class="card-title">{{ book.title.upper }}</h3>
            <p class="card-text">${{ book.price }}</p>
            <p class="card-text">{{ book.publisher }}</p>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h2>{{ book.title }}</h2>
<p>Price: {{ book.price }}</p>
<p>Publisher: {{ book.publisher }}</p>
<p><a href="{% url 'myapp:index' %}">Go to index page</a></p>
<p><a href="{% url 'myapp:about' %}">Go to about page</a></p>

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if last_login %}
        <p class="login-status">( Last login was {{ last_login }} )</p>
    {% else %}
        <p class="login-status">( Your last login was more than one hour ago )</p>
    {% endif %}

    <div class="body-content">
        {% if booklist %}
            {#            <h2 class="display-4">Books:</h2>#}
            <ol class="list-group">
                {% for book in booklist %}
                    <li class="list-group-item"><a href="{% url 'myapp:detail' book.id %}">{{ book.title }} </a></li>
                {% endfor %}
            </ol>

        {% else %}
            <strong>There are no available books!</strong>
        {% endif %}

        <br><br>
        <a class="btn btn-info" href="{% url 'myapp:place_order' %}">Place order</a>
        <a class="btn btn-warning" href="{% url 'myapp:review' %}">Review book</a>
        <a class="btn btn-secondary" href="{% url 'myapp:orders' %}">Orders</a>
        {#        <img src="{{ request.user.member.image.url }}" alt="Image of the user">#}
    </div>
{% endblock %}

myapp/templates/myapp/invalid.html
{% extends 'myapp/base.html' %}

{% block title %}Invalid{% endblock %}

{% block body_block %}
    <h3 style="margin-top: 100px;">{{ message }}</h3>
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}

{% block title %}Orders{% endblock %}

{% block body_block %}
    <div class="register-form" style="margin-top: 100px;">
        {% if orders %}

            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Books</th>
                    <th scope="col">Order Type</th>
                    <th scope="col">Order Date</th>
                </tr>
                </thead>
                <tbody>
                {% for order, book in new_list %}
                    <tr>
                        <td>{{ book }}</td>

                        <td>
                            {% if order.order_type == 0 %}
                                Purchase
                            {% else %}
                                Borrow
                            {% endif %}
                        </td>
                        <td>{{ order.order_date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <strong>There are no available orders!</strong>
        {% endif %}
    </div>

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block title %}Placed order{% endblock %}

{% block myhdg %}Hello {{ name }}{% endblock %}

{% block body_block %}
    <div class="body-content">
        {% if books %}
            <h2 class="display-5">List of ordered Books: </h2>
            <hr>
            <ol class="list-group">
                {% for book in books %}
                    <li class="list-group-item">{{ book.title }}</li>
                {% endfor %}
            </ol>

        {% else %}
            <strong>There are no available books!</strong>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Place order{% endblock %}

{% block body_block %}
    <div class="register-form">
        <form action="{% url 'myapp:place_order' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" name="submit1" class="btn btn-success register-submit" value="Submit"/>
        </form>
    </div>

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block myhdg %}{% endblock %}

{% block body_block %}
    <div class="register-form">
        <form action="{% url 'myapp:register' %}" method="post" enctype="multipart/form-data" class="form-group">
            {% csrf_token %}

            {{ form.username|as_crispy_field }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.password1|as_crispy_field }}
                </div>

                <div class="form-group col-md-6">
                    {{ form.password2|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.first_name|as_crispy_field }}
                </div>

                <div class="form-group col-md-6">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
            {{ form.status|as_crispy_field }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.address|as_crispy_field }}
                </div>

                <div class="form-group col-md-2">
                    {{ form.city|as_crispy_field }}
                </div>

                <div class="form-group col-md-2">
                    {{ form.province|as_crispy_field }}
                </div>
            </div>
            {{ form.profile_image|as_crispy_field }}
            {{ form.auto_renew|as_crispy_field }}

            <input type="submit" name="submit1" class="btn btn-success register-submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

myapp/templates/myapp/results.html
{% extends 'myapp/base.html' %}

{% block title %}Result{% endblock %}

{% block myhdg %}Hello {{ name }}{% endblock %}

{% block body_block %}
    <div class="body-content">
        {% if booklist %}
            {% if category %}
                <h2 class="display-5">List of Books of category: {{ category }}</h2>
            {% else %}
                <h2 class="display-5">List of Books </h2>
            {% endif %}
            <hr>
            <ol class="list-group">
                {% for book in booklist %}
                    <li class="list-group-item">{{ book.title }}</li>
                {% endfor %}
            </ol>

        {% else %}
            <strong>There are no available books!</strong>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/myapp/review.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Review{% endblock %}

{% block body_block %}
    <div class="register-form">
        <form action="{% url 'myapp:review' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" name="submit1" class="btn btn-success register-submit" value="Submit"/>
        </form>
    </div>
{% endblock %}